apiVersion: v1
kind: Pod
metadata:
  name: docker-volume
spec:
  volumes:
  - name: docker-socket
    hostPath: 
      path: /var/run/docker.sock
      type: Socket
  containers:
  - name: docker
    image: docker
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock

# Do "docker ps -a" in side the container to see containers running in host