apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-configmap
spec:
  selector:
    matchLabels:
      app: node-configmap
  template:
    metadata:
      labels:
        app: node-configmap
    spec:     
      containers:
      - name: my-nginx
        image: nginx:alpine
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      - name: html-updater
        image: alpine
        command:  ['sh', '-c']
        args:
        - while true; do echo "My name is - $MY_NAME <br> Mom name is - $MOTHER_NAME <br> Father name is - $FATHER_NAME <br> Brother name is - $BROTHER_NAME <br><br>" >> /html/index.html; sleep 10; done
        volumeMounts:
        - name: html
          mountPath: /html
        - name: app-config-vol
          mountPath: /etc/config
        envFrom:
        - configMapRef:
            name: app-settings
        env:
        - name: MY_NAME_SPECIFIC
          valueFrom:
            configMapKeyRef:
              name: app-settings
              key: MY_NAME
      volumes:
      - name: app-config-vol
        configMap:
          name: app-settings
      - name: html
        emptyDir: {} #lifecycle tied to Pod

---

apiVersion: v1
kind: Service
metadata:
  name: node-configmap-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: node-configmap
  ports:
  - name: "80"
    port: 80
    targetPort: 80